"""Your descriptive migration message

Revision ID: 9c4546eb7f32
Revises: b77590c83d1a
Create Date: 2025-05-12 17:38:47.852684

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9c4546eb7f32'
down_revision = 'b77590c83d1a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('inventory', schema=None) as batch_op:
        batch_op.add_column(sa.Column('reorder_level', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('location', sa.String(length=100), nullable=True))
        batch_op.drop_column('low_stock_threshold')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('inventory', schema=None) as batch_op:
        batch_op.add_column(sa.Column('low_stock_threshold', sa.INTEGER(), nullable=True))
        batch_op.drop_column('location')
        batch_op.drop_column('reorder_level')

    # ### end Alembic commands ###
