"""Add status column to OrderItem table

Revision ID: ffc112b5d83a
Revises: 9c4546eb7f32
Create Date: 2025-05-14 14:21:12.548770

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ffc112b5d83a'
down_revision = '9c4546eb7f32' # Ensure this points to the previous migration if one exists, otherwise None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order_item', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', sa.String(length=50), nullable=False, server_default='Pending'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order_item', schema=None) as batch_op:
        batch_op.drop_column('status')

    # ### end Alembic commands ###

